// <auto-generated />
using CQCViewer.Shared.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CareHomeData.Ui.Console.Migrations
{
    [DbContext(typeof(SQLiteContext))]
    partial class SQLiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("CQCViewer.Shared.Models.ProviderDetail", b =>
                {
                    b.Property<string>("providerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("alsoKnownAs")
                        .HasColumnType("TEXT");

                    b.Property<string>("localAuthority")
                        .HasColumnType("TEXT");

                    b.Property<string>("locationIds")
                        .HasColumnType("TEXT");

                    b.Property<string>("mainPhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("organisationType")
                        .HasColumnType("TEXT");

                    b.Property<string>("postalAddressCounty")
                        .HasColumnType("TEXT");

                    b.Property<string>("postalAddressLine1")
                        .HasColumnType("TEXT");

                    b.Property<string>("postalAddressLine2")
                        .HasColumnType("TEXT");

                    b.Property<string>("postalAddressTownCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("postalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("region")
                        .HasColumnType("TEXT");

                    b.Property<string>("registrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("registrationStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("website")
                        .HasColumnType("TEXT");

                    b.HasKey("providerId");

                    b.ToTable("ProviderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
